export const country = [
  {
    id: 1,
    img: "assets/img1.jpg",
    country: "Ghana",
  },
  {
    id: 2,
    img: "assets/img2.jpg",
    country: "Paris",
  },
  {
    id: 3,
    img: "assets/img4.jpg",
    country: "Spain",
  },
];

export const posts = [
  {
    id: 1,
    title: "Exploring The 50th State Fair 2022",
    img: "../../assets/img4.jpg",
    cats: "DESIGN",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 2,
    title: "The Story Of Photography Has Just Gone Viral!2",
    img: "assets/img5.jpg",
    cats: "PHOTOGRAPHY",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 3,
    title: "Seven Ways To Learn Lifestyle Effectively.",
    img: "assets/img3.jpg",
    cats: "VIDEOS",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 4,
    title: "20 Wonderful Music. Number 16 is Absolutely Stunning.",
    img: "assets/img4.jpg",
    cats: "MUSIC",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 5,
    title: "7 Lessons I've Learned From Travel.",
    img: "assets/img2.jpg",
    cats: "TRAVEL",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 6,
    title: "Seven Stereotypes About Videos That Aren't Always True",
    img: "assets/img4.jpg",
    cats: "VIDEOS",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 7,
    title: "The Seven Common Stereotypes When It Comes To Photography.",
    img: "assets/img8.jpg",
    cats: "PHOTOGRAPHY",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 8,
    title: "The Cheapest Way To Earn Your Free Ticket To Travel.",
    img: "assets/img6.jpg",
    cats: "TRAVEL",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 9,
    title: "How Music Is Going To Change Your Business Strategies",
    img: "assets/img9.jpg",
    cats: "MUSIC",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
  {
    id: 10,
    title: "Is Lifestyle Any Good? Ten Ways You Can Be Certain.",
    img: "assets/img10.jpg",
    cats: "LIFESTYLE",
    author: "Simon Oware",
    date: "Feb 26, 2022",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto iure possimus, delectus consectetur quos sunt minima quod mollitia ea repudiandae! Nesciunt ab molestias assumenda adipisci blanditiis quos perferendis ipsa illo?",
    btn: "Read More",
  },
];
